{% set version = "2.5.4" %}

package:
  name: magma
  version: {{ version }}

source:
  url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
  sha256: 7734fb417ae0c367b418dea15096aef2e278a423e527c615aab47f0683683b67
  patches:
    - cmakelists.patch
    - thread_queue.patch
    - cudaPointerAttributes.patch   # [cuda_compiler_version in ("11.0", "11.1")]

build:
  number: 0
  skip: true  # [not linux64 or cuda_compiler_version=="None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make  # [unix]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - liblapack
    - libblas

test:
  commands:
    - test -f $PREFIX/include/magma.h  # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}   # [unix]

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  summary: Matrix Algebra on GPU and Multicore Architectures
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - isuruf
