{% set version = "2.7.1" %}

package:
  name: magma
  version: {{ version }}

source:
  url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
  sha256: 22351e6edebd1d10c120bf2fa2216dbe8673c6c8417ae4db4f145b9c17b95cba

build:
  number: 0
  skip: true  # [cuda_compiler_version=="None"]
  run_exports:
    - {{ pin_subpackage('magma', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.20
    - make  # [unix]
    - ninja  # [win]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - m2-sed  # [win]
  host:
    - liblapack
    - libblas

test:
  commands:
    - test -f $PREFIX/include/magma.h  # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}   # [unix]
    - test -f $PREFIX/lib/libmagma_sparse${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_PREFIX%\include\magma.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma_sparse.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma_sparse.dll exit 1  # [win]

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  summary: Matrix Algebra on GPU and Multicore Architectures
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - carterbox
    - conda-forge/pytorch-cpu
