conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_ppc64le: default
  linux_aarch64: default
# Builds can take 3 hours Travis was timing-out
idle_timeout_minutes: 240
azure:
  store_build_artifacts: True
